image: python:3.12

# This folder is cached between builds (http://docs.gitlab.com/ce/ci/yaml/README.html#cache)
cache:
    paths:
        - ~/.cache/pip/

before_script:
    - python -V

stages:
    - test
    - style
    - docs
    # - deploy

# pep8:
#     stage: style
#     before_script:
#         - pip install -r ci/pycodestyle_requirements.txt
#     script:
#         - ./ci/pycodestyle_runner.sh
#     artifacts:
#         paths:
#             - public/pycodestyle.txt

pylint:
    stage: style
    before_script:
        - pip install -r ci/pylint_requirements.txt
    script:
        - chmod u+r+x ./ci/pylint_runner.sh
        - ./ci/pylint_runner.sh
    artifacts:
        paths:
            - public/pylint.svg
            - public/pylint.html

test:
    stage: test
    before_script:
        - pip install -r requirements.txt
        - python manage.py makemigrations
        - python manage.py migrate
    script:
        - coverage run manage.py test
        - coverage report --omit=manage.py
        - coverage html --omit=manage.py
        - mkdir public
        - mv htmlcov public/coverage
    artifacts:
        paths:
            - public/coverage

sphinx:
    stage: docs
    before_script:
        - pip install -r ci/sphinx_requirements.txt
    script:
        - cd docs
        - export PYTHONPATH=..
        - make html
        - cd ..
        - mv docs/build/html public/docs
    artifacts:
        paths:
            - public/docs
# pages:
#   stage: deploy
#   script:
#   - echo 'Publish pages data'
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
