name: Documentation

on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install sphinx dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci/sphinx_requirements.txt

    - name: Build documentation
      run: |
        chmod u+x ./ci/sphinx_runner.sh
        ./ci/sphinx_runner.sh

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: public/ 