name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  style:
    uses: ./.github/workflows/style.yml

  docs:
    uses: ./.github/workflows/docs.yml

  deploy:
    needs: [test, style, docs]
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yml